### №1. Степени двойки.

Теперь выведите все степени двойки в диапазоне от [l, r]* включительно

*r - теперь может принимать большие значения. Оптимизируйте свой код.

Входные данные:

$1<=l<=r<=10^{10}$

Выведите все числа в одну строку через пробел.

```bash
9 512
```

```bash
16
32
64
128
256
512
```

In [ ]:
l, r = map(int, input().split())
num = 1

while num <= r:
  if num >= l and num <= r:
    print(num)
  num = num * 2

0 100000000000000000000000000000000000000000000000
1
2
4
8
16
32
64
128
256
512
1024
2048
4096
8192
16384
32768
65536
131072
262144
524288
1048576
2097152
4194304
8388608
16777216
33554432
67108864
134217728
268435456
536870912
1073741824
2147483648
4294967296
8589934592
17179869184
34359738368
68719476736
137438953472
274877906944
549755813888
1099511627776
2199023255552
4398046511104
8796093022208
17592186044416
35184372088832
70368744177664
140737488355328
281474976710656
562949953421312
1125899906842624
2251799813685248
4503599627370496
9007199254740992
18014398509481984
36028797018963968
72057594037927936
144115188075855872
288230376151711744
576460752303423488
1152921504606846976
2305843009213693952
4611686018427387904
9223372036854775808
18446744073709551616
36893488147419103232
73786976294838206464
147573952589676412928
295147905179352825856
590295810358705651712
1180591620717411303424
2361183241434822606848
4722366482869645213696
9444732965739290427392
18889465931478580854784
37778931862957161709568
75557863725914323419136
151115727451828646838272
302231454903657293676544
604462909807314587353088
1208925819614629174706176
2417851639229258349412352
4835703278458516698824704
9671406556917033397649408
19342813113834066795298816
38685626227668133590597632
77371252455336267181195264
154742504910672534362390528
309485009821345068724781056
618970019642690137449562112
1237940039285380274899124224
2475880078570760549798248448
4951760157141521099596496896
9903520314283042199192993792
19807040628566084398385987584
39614081257132168796771975168
79228162514264337593543950336
158456325028528675187087900672
316912650057057350374175801344
633825300114114700748351602688
1267650600228229401496703205376
2535301200456458802993406410752
5070602400912917605986812821504
10141204801825835211973625643008
20282409603651670423947251286016
40564819207303340847894502572032
81129638414606681695789005144064
162259276829213363391578010288128
324518553658426726783156020576256
649037107316853453566312041152512
1298074214633706907132624082305024
2596148429267413814265248164610048
5192296858534827628530496329220096
10384593717069655257060992658440192
20769187434139310514121985316880384
41538374868278621028243970633760768
83076749736557242056487941267521536
166153499473114484112975882535043072
332306998946228968225951765070086144
664613997892457936451903530140172288
1329227995784915872903807060280344576
2658455991569831745807614120560689152
5316911983139663491615228241121378304
10633823966279326983230456482242756608
21267647932558653966460912964485513216
42535295865117307932921825928971026432
85070591730234615865843651857942052864
170141183460469231731687303715884105728
340282366920938463463374607431768211456
680564733841876926926749214863536422912
1361129467683753853853498429727072845824
2722258935367507707706996859454145691648
5444517870735015415413993718908291383296
10889035741470030830827987437816582766592
21778071482940061661655974875633165533184
43556142965880123323311949751266331066368
87112285931760246646623899502532662132736
174224571863520493293247799005065324265472
348449143727040986586495598010130648530944
696898287454081973172991196020261297061888
1393796574908163946345982392040522594123776
2787593149816327892691964784081045188247552
5575186299632655785383929568162090376495104
11150372599265311570767859136324180752990208
22300745198530623141535718272648361505980416
44601490397061246283071436545296723011960832
89202980794122492566142873090593446023921664
178405961588244985132285746181186892047843328
356811923176489970264571492362373784095686656
713623846352979940529142984724747568191373312
1427247692705959881058285969449495136382746624
2854495385411919762116571938898990272765493248
5708990770823839524233143877797980545530986496
11417981541647679048466287755595961091061972992
22835963083295358096932575511191922182123945984
45671926166590716193865151022383844364247891968
91343852333181432387730302044767688728495783936

### №2. Делители числа.
Выведите все делители числа от 1 до $n$ включительно.

Входные данные:
$1<=n<=10^7$

*Будьте аккуратны с квадратами

```bash
21
```
```bash
1 3 7 21
```

In [ ]:
n = int(input())

count = 1

for i in range(n):
  if n % count == 0:
    print(count)

  count += 1

111
1
3
37
111

### №3. Високосный год.

По номеру года определите, является ли данный год високосным.

Напомним, что високосными являются года, номера которых кратны 4, но не кратны 100, а также года, номера которых кратны 400

Выведите `Да` или `Нет` в зависимости от ответа на вопрос задачи.

Входные данные:
```bash
2007
```

Результат:
```bash
Нет
```

In [ ]:
year = int(input())

if year % 4 == 0 and year % 100 != 0:
  print('Да')
elif year % 400 == 0:
  print('Да')
else:
  print('Нет')

1999
Нет

### №4. Шахматы.

Поле шахматной доски определяется парой натуральных чисел, каждое из которых не превосходит 8.

По введенным координатам двух полей (𝑘,𝑙) и (𝑚,𝑛) выясните, угрожает ли ферзь, находящийся на поле (𝑘,𝑙), полю (𝑚,𝑛)?

Выведите `Да` или `Нет` в зависимости от ответа на вопрос задачи.

Входные данные:
```bash
1 1 2 2
```

Результат:
```bash
Да
```

In [ ]:
k, l, m, n = map(int, input().split())

if abs(m - k) == abs(n - l):
  print('Да')
else:
  print('Нет')

### №5 k-ая секунда суток

Идёт 𝑘-я секунда суток. Определите, сколько целых часов ℎ и целых минут m прошло с начала суток. Например, если

$𝑘=13257=3⋅3600+40⋅60+57$

Входные данные:
```bash
13257
```

Результат:
```bash
3 hours 40 minutes
```

In [ ]:
k = int(input())
hours = k // 3600
minutes = (k % 3600) // 60

print(f'{hours} hours {minutes} minutes')

13257
3 hours 40 minutes

### №6 Елочка

Выведите елочку высоты $n$ по шаблону из примера

Входные данные:
```bash
3
```

Результат:
```bash
  *
 ***
*****
```

In [ ]:
n = int(input())
count = n
star_count = 1

for i in range(n):
  print(' ' * count + '*' * star_count)
  count -= 1
  star_count += 2

Buffered data was truncated after reaching the output size limit.

### №7 Максимум и минимум

Дана последовательность, состоящая из $n$ чисел. Найти в ней максимум и минимум.

*Запрещено использование функций min и max


Входные данные - число $n > 0$ и числа на разных строчках $-1000 <= a_i <= 1000$:
```bash
3
5
6
7
```

Выходные данные:
```bash
5 7
```

In [ ]:
n = int(input())
max = int(input())
min = max

for i in range(n - 1):
  x = int(input())

  if x > max:
    max = x
  if x < min:
    min = x

print(min, max)

6
10
4
20
1
19
16
1 20

### №8 Минимум и минимум

Дана последовательность, состоящая из $n$ чисел. Найти в ней два самых маленьких числа.

*Запрещено использование функций min и max

Входные данные - число $n > 0$ и числа на разных строчках $-1000 <= a_i <= 1000$:
```bash
3
5
6
7
```

Выходные данные:
```bash
5 6
```

In [ ]:
n = int(input())

min1 = int(input())
min2 = int(input())

if min2 < min1:
  min1, min2 = min2, min1

for i in range(n - 2):
  x = int(input())

  if x < min1:
    min2 = min1
    min1 = x

print(min1, min2)

6
10
4
20
1
19
16
1 4